server:
  port: 8080

spring:
  application:
    name: pruebatecnica_w2m
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true

kafka:
  bootstrap-servers: kafka:29092