INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (1, 'Explorer');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (2, 'Fighter');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (3, 'Transport');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (4, 'Battleship');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (5, 'Research Vessel');


INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (1, 'Enterprise', 299792.458, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (2, 'Millennium Falcon', 1050.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (3, 'X-Wing', 3000.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (4, 'Serenity', 600.5, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (5, 'Galactica', 500.2, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (6, 'Slave I', 1500.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (7, 'Nostromo', 250.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (8, 'Discovery One', 10000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (9, 'Heart of Gold', 200000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (10, 'Razor Crest', 800.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (11, 'Executor', 15000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (12, 'Andromeda', 18000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (13, 'USS Defiant', 7500.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (14, 'Event Horizon', 50000.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (15, 'Red Dwarf', 100.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (16, 'Voyager', 100000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (17, 'Eagle 5', 700.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (18, 'Prometheus', 20000.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (19, 'Bebop', 950.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (20, 'Thunderbird 3', 1250.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (21, 'Daedalus', 7500.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (22, 'Sulaco', 2000.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (23, 'Icarus II', 9000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (24, 'Hermes', 8500.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (25, 'Avalon', 7500.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (26, 'Infinity', 12000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (27, 'Ghost', 1200.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (28, 'Valkyrie', 8000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (29, 'F-302', 3000.0, 2);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (30, 'Hunter-Gratzner', 400.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (31, 'Loki', 650.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (32, 'Asgard', 5000.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (33, 'Moya', 3000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (34, 'Pegasus', 8000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (35, 'Resolute', 4000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (36, 'Endurance', 20000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (37, 'Orion', 9000.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (38, 'Leviathan', 600.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (39, 'Rocinante', 11000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (40, 'Covenant', 7000.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (41, 'Minerva', 6000.0, 1);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (42, 'Aries', 2000.0, 3);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (43, 'Athena', 8000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (44, 'Goliath', 10000.0, 4);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (45, 'Phoenix', 8500.0, 5);
INSERT INTO SPACE_SHIPS (id, name, speed, F_ID_TYPE) VALUES (46, 'Genesis', 9500.0, 1);
