INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (1, 'Explorer');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (2, 'Fighter');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (3, 'Transport');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (4, 'Battleship');
INSERT INTO SPACE_SHIP_TYPES (id, name) VALUES (5, 'Research Vessel');


INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Enterprise', 299792.458, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Millennium Falcon', 1050.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('X-Wing', 3000.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Serenity', 600.5, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Galactica', 500.2, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Slave I', 1500.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Nostromo', 250.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Discovery One', 10000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Heart of Gold', 200000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Razor Crest', 800.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Executor', 15000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Andromeda', 18000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('USS Defiant', 7500.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Event Horizon', 50000.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Red Dwarf', 100.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Voyager', 100000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Eagle 5', 700.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Prometheus', 20000.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Bebop', 950.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Thunderbird 3', 1250.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Daedalus', 7500.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Sulaco', 2000.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Icarus II', 9000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Hermes', 8500.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Avalon', 7500.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Infinity', 12000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Ghost', 1200.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Valkyrie', 8000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('F-302', 3000.0, 2);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Hunter-Gratzner', 400.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Loki', 650.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Asgard', 5000.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Moya', 3000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Pegasus', 8000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Resolute', 4000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Endurance', 20000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Orion', 9000.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Leviathan', 600.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Rocinante', 11000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Covenant', 7000.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Minerva', 6000.0, 1);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Aries', 2000.0, 3);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Athena', 8000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Goliath', 10000.0, 4);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Phoenix', 8500.0, 5);
INSERT INTO SPACE_SHIPS (name, speed, F_ID_TYPE) VALUES ('Genesis', 9500.0, 1);
